### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by AnshuBhatiaGit** [danielstern/redux-saga-shopping-cart-server#3]
I cloned the code but it is not showing the data on localhost:8081 I changed the port number to 4445 but still cannot access the data. 
My node version is 10.18.0

Please help as I am stuck moving with the course on PluralSight.

**Comment by AnshuBhatiaGit** [comment]
I changed the server to port 4440 and it works. Thanks

**Comment by danielstern** [comment]
Good stuff!
